// EduGuard AI — Student Data
// Synthetic dataset representing CHARUSAT students across departments

const STUDENTS = [
  // ─── HIGH RISK ──────────────────────────────────────────────────────────
  { id:'CE001', name:'Arjun Patel',     dept:'Computer Engineering',       deptCode:'CE',   year:2, sem:3, rollNo:'23CE001', email:'23ce001@charusat.ac.in', advisor:'Dr. Ronak Patel',         guardian:'Ramesh Patel',   attendance:52, marks:38, assignments:55, lab:65, participation:40, financialStress:7, socialIssues:3, backlogs:2, trend:'declining', notes:'Financial difficulties reported. Frequently missing lab sessions. Father is daily-wage worker.' },
  { id:'IT001', name:'Priya Singh',     dept:'Information Technology',     deptCode:'IT',   year:1, sem:1, rollNo:'26IT001', email:'26it001@charusat.ac.in', advisor:'Dr. Hemant Yadav',        guardian:'Suresh Singh',   attendance:68, marks:42, assignments:48, lab:72, participation:25, financialStress:5, socialIssues:8, backlogs:3, trend:'declining', notes:'Social adjustment struggles. Migrated from remote village. Very low classroom participation.' },
  { id:'ME001', name:'Rohan Mehta',     dept:'Mechanical Engineering',     deptCode:'ME',   year:3, sem:5, rollNo:'24ME001', email:'24me001@charusat.ac.in', advisor:'Dr. Abhishek Sarvarkar',  guardian:'Dinesh Mehta',   attendance:48, marks:35, assignments:42, lab:55, participation:38, financialStress:8, socialIssues:4, backlogs:4, trend:'declining', notes:'4 active backlogs. Father lost job. Considering dropping out. Urgent financial & academic support needed.' },
  { id:'AI001', name:'Zara Khan',       dept:'AI & Machine Learning',      deptCode:'AIML', year:2, sem:3, rollNo:'25AIML001',email:'25aiml001@charusat.ac.in',advisor:'Dr. Hardik Jaiswal',   guardian:'Imran Khan',     attendance:65, marks:35, assignments:40, lab:60, participation:45, financialStress:4, socialIssues:7, backlogs:2, trend:'declining', notes:'Personal issues at home impacting academics. Sudden marks drop this semester vs last.' },
  { id:'CSE001',name:'Dev Sharma',      dept:'Computer Science & Engg',    deptCode:'CSE',  year:1, sem:1, rollNo:'26CSE001', email:'26cse001@charusat.ac.in', advisor:'Pinal Hansora',          guardian:'Vijay Sharma',   attendance:45, marks:42, assignments:50, lab:48, participation:35, financialStress:6, socialIssues:3, backlogs:0, trend:'declining', notes:'First-year student struggling to adapt. Homesick. City student but financially stressed.' },
  { id:'EC001', name:'Kavya Nair',      dept:'Electronics & Comm',         deptCode:'EC',   year:2, sem:3, rollNo:'25EC001', email:'25ec001@charusat.ac.in', advisor:'Dr. Miral Desai',         guardian:'Rajan Nair',     attendance:58, marks:45, assignments:52, lab:62, participation:42, financialStress:9, socialIssues:2, backlogs:1, trend:'stable',   notes:'Working part-time at local shop to support family. Attendance suffering as a result.' },
  { id:'CE002', name:'Harsh Patel',     dept:'Computer Engineering',       deptCode:'CE',   year:3, sem:5, rollNo:'24CE002', email:'24ce002@charusat.ac.in', advisor:'Dr. Ronak Patel',         guardian:'Haresh Patel',   attendance:50, marks:38, assignments:45, lab:52, participation:32, financialStress:6, socialIssues:3, backlogs:4, trend:'declining', notes:'4 active backlogs across Sem 3 and 4. Requires immediate faculty & academic coordinator intervention.' },
  { id:'IT002', name:'Sneha Joshi',     dept:'Information Technology',     deptCode:'IT',   year:3, sem:5, rollNo:'24IT002', email:'24it002@charusat.ac.in', advisor:'Dr. Hemant Yadav',        guardian:'Prakash Joshi',  attendance:48, marks:44, assignments:58, lab:55, participation:40, financialStress:4, socialIssues:6, backlogs:1, trend:'declining', notes:'Mental health concerns flagged by roommate. Counselling referral recommended.' },

  // ─── MEDIUM RISK ─────────────────────────────────────────────────────────
  { id:'CSE002',name:'Rahul Gupta',     dept:'Computer Science & Engg',    deptCode:'CSE',  year:2, sem:3, rollNo:'25CSE002', email:'25cse002@charusat.ac.in', advisor:'Pinal Hansora',          guardian:'Anil Gupta',     attendance:70, marks:52, assignments:65, lab:72, participation:55, financialStress:4, socialIssues:2, backlogs:1, trend:'stable',   notes:'Average performance. One backlog. Needs targeted subject support.' },
  { id:'CE003', name:'Ananya Sharma',   dept:'Computer Engineering',       deptCode:'CE',   year:1, sem:1, rollNo:'26CE003', email:'26ce003@charusat.ac.in', advisor:'Dr. Ronak Patel',         guardian:'Suresh Sharma',  attendance:72, marks:55, assignments:60, lab:75, participation:50, financialStress:4, socialIssues:2, backlogs:0, trend:'stable',   notes:'First-year transition. Moderate financial stress. Manageable with monitoring.' },
  { id:'IT003', name:'Vivek Kumar',     dept:'Information Technology',     deptCode:'IT',   year:3, sem:5, rollNo:'24IT003', email:'24it003@charusat.ac.in', advisor:'Dr. Hemant Yadav',        guardian:'Sanjay Kumar',   attendance:78, marks:58, assignments:68, lab:74, participation:52, financialStress:3, socialIssues:2, backlogs:1, trend:'declining', notes:'Slight downward trend noted. One backlog. Close to high risk threshold.' },
  { id:'AI002', name:'Meera Pillai',    dept:'AI & Machine Learning',      deptCode:'AIML', year:1, sem:1, rollNo:'26AIML002',email:'26aiml002@charusat.ac.in',advisor:'Dr. Hardik Jaiswal',   guardian:'Krishnan Pillai', attendance:74, marks:48, assignments:55, lab:70, participation:48, financialStress:3, socialIssues:5, backlogs:0, trend:'stable',   notes:'Social integration challenges. Performance dipping in core subjects.' },
  { id:'ME002', name:'Karan Shah',      dept:'Mechanical Engineering',     deptCode:'ME',   year:2, sem:3, rollNo:'25ME002', email:'25me002@charusat.ac.in', advisor:'Dr. Abhishek Sarvarkar',  guardian:'Yogesh Shah',    attendance:74, marks:58, assignments:65, lab:60, participation:45, financialStress:3, socialIssues:2, backlogs:1, trend:'stable',   notes:'Lab attendance concern. Otherwise manageable. One backlog in Thermodynamics.' },
  { id:'EC002', name:'Divya Joshi',     dept:'Electronics & Comm',         deptCode:'EC',   year:1, sem:1, rollNo:'26EC002', email:'26ec002@charusat.ac.in', advisor:'Dr. Miral Desai',         guardian:'Manish Joshi',   attendance:75, marks:60, assignments:70, lab:78, participation:58, financialStress:3, socialIssues:2, backlogs:0, trend:'stable',   notes:'Borderline risk. Minor financial concern but manageable.' },
  { id:'CSE003',name:'Aditya Verma',    dept:'Computer Science & Engg',    deptCode:'CSE',  year:3, sem:5, rollNo:'24CSE003', email:'24cse003@charusat.ac.in', advisor:'Pinal Hansora',          guardian:'Rakesh Verma',   attendance:73, marks:50, assignments:62, lab:70, participation:50, financialStress:2, socialIssues:2, backlogs:2, trend:'stable',   notes:'2 backlogs. Performance stable but not improving. Needs academic guidance.' },
  { id:'CE004', name:'Nisha Patel',     dept:'Computer Engineering',       deptCode:'CE',   year:2, sem:3, rollNo:'25CE004', email:'25ce004@charusat.ac.in', advisor:'Dr. Ronak Patel',         guardian:'Ketan Patel',    attendance:80, marks:58, assignments:65, lab:78, participation:60, financialStress:2, socialIssues:1, backlogs:0, trend:'stable',   notes:'Borderline medium-low risk. Good attendance but marks need improvement.' },
  { id:'IT004', name:'Siddharth Roy',   dept:'Information Technology',     deptCode:'IT',   year:1, sem:1, rollNo:'26IT004', email:'26it004@charusat.ac.in', advisor:'Dr. Hemant Yadav',        guardian:'Amit Roy',       attendance:72, marks:55, assignments:60, lab:68, participation:35, financialStress:3, socialIssues:3, backlogs:0, trend:'stable',   notes:'Low participation. First-year adjustment period. Needs engagement.' },
  { id:'AI003', name:'Pooja Rao',       dept:'AI & Machine Learning',      deptCode:'AIML', year:3, sem:5, rollNo:'24AIML003',email:'24aiml003@charusat.ac.in',advisor:'Dr. Hardik Jaiswal',   guardian:'Venkat Rao',     attendance:76, marks:60, assignments:68, lab:75, participation:58, financialStress:2, socialIssues:2, backlogs:1, trend:'improving', notes:'Improving trend. One remaining backlog. On track.' },
  { id:'ME003', name:'Rahil Shaikh',    dept:'Mechanical Engineering',     deptCode:'ME',   year:2, sem:3, rollNo:'25ME003', email:'25me003@charusat.ac.in', advisor:'Dr. Abhishek Sarvarkar',  guardian:'Arif Shaikh',    attendance:69, marks:54, assignments:62, lab:65, participation:48, financialStress:5, socialIssues:3, backlogs:1, trend:'stable',   notes:'Moderate financial pressure. Attendance slightly below threshold.' },

  // ─── LOW RISK ────────────────────────────────────────────────────────────
  { id:'CE005', name:'Aarav Shah',      dept:'Computer Engineering',       deptCode:'CE',   year:2, sem:3, rollNo:'25CE005', email:'25ce005@charusat.ac.in', advisor:'Dr. Ronak Patel',         guardian:'Nilesh Shah',    attendance:92, marks:78, assignments:88, lab:95, participation:82, financialStress:1, socialIssues:0, backlogs:0, trend:'improving', notes:'Top performer in the department. Excellent engagement and leadership.' },
  { id:'IT005', name:'Riya Desai',      dept:'Information Technology',     deptCode:'IT',   year:3, sem:5, rollNo:'24IT005', email:'24it005@charusat.ac.in', advisor:'Dr. Hemant Yadav',        guardian:'Paresh Desai',   attendance:88, marks:72, assignments:85, lab:90, participation:78, financialStress:1, socialIssues:0, backlogs:0, trend:'improving', notes:'Consistent performer. Improving each semester. Placement ready.' },
  { id:'CSE004',name:'Shreya Kumar',    dept:'Computer Science & Engg',    deptCode:'CSE',  year:1, sem:1, rollNo:'26CSE004', email:'26cse004@charusat.ac.in', advisor:'Pinal Hansora',          guardian:'Manoj Kumar',    attendance:95, marks:82, assignments:92, lab:94, participation:88, financialStress:0, socialIssues:0, backlogs:0, trend:'improving', notes:'Excellent student. Strong academic foundation from day 1.' },
  { id:'AI004', name:'Yash Mehta',      dept:'AI & Machine Learning',      deptCode:'AIML', year:2, sem:3, rollNo:'25AIML004',email:'25aiml004@charusat.ac.in',advisor:'Dr. Hardik Jaiswal',   guardian:'Bharat Mehta',   attendance:85, marks:70, assignments:82, lab:88, participation:75, financialStress:1, socialIssues:0, backlogs:0, trend:'stable',   notes:'Good consistent performer. Stable across all metrics.' },
  { id:'ME004', name:'Kritika Singh',   dept:'Mechanical Engineering',     deptCode:'ME',   year:1, sem:1, rollNo:'26ME004', email:'26me004@charusat.ac.in', advisor:'Dr. Abhishek Sarvarkar',  guardian:'Tejpal Singh',   attendance:90, marks:75, assignments:85, lab:88, participation:80, financialStress:1, socialIssues:0, backlogs:0, trend:'improving', notes:'Strong first-year performance. Well-adapted to campus life.' },
  { id:'EC003', name:'Mihir Patel',     dept:'Electronics & Comm',         deptCode:'EC',   year:3, sem:5, rollNo:'24EC003', email:'24ec003@charusat.ac.in', advisor:'Dr. Miral Desai',         guardian:'Dinesh Patel',   attendance:87, marks:68, assignments:82, lab:85, participation:72, financialStress:1, socialIssues:0, backlogs:0, trend:'stable',   notes:'Solid performer. Minor improvement needed in marks. Zero backlogs.' },
  { id:'CE006', name:'Tanvi Nair',      dept:'Computer Engineering',       deptCode:'CE',   year:4, sem:7, rollNo:'23CE006', email:'23ce006@charusat.ac.in', advisor:'Dr. Ronak Patel',         guardian:'Gopalan Nair',   attendance:96, marks:88, assignments:100,lab:97, participation:92, financialStress:0, socialIssues:0, backlogs:0, trend:'improving', notes:'Outstanding student. Campus placement interviews cleared. Role model for juniors.' },
];

const DEPARTMENTS = ['Computer Engineering','Information Technology','AI & Machine Learning','Computer Science & Engg','Mechanical Engineering','Electronics & Comm'];
const DEPT_COLORS  = { CE:'#6c63ff', IT:'#4facfe', AIML:'#00f2fe', CSE:'#26de81', ME:'#ff9f43', EC:'#ff4757' };
